### ISSUE TITLE
Create a RethinkDB Adapter

### ISSUE THREAD

**Issue by MiguhRuiz** [nodefruit/fruit#3]
I want to create a RethinkDB Adapter to use with fruit. Do I have to create it in my personal profile? Any specific conditions?

**Comment by Javascipt** [comment]
Ok , I'm going to invite you into the organization, I'll create a the repo so that you can start working on it. All you need to know is that the unit tests should be the same as other adapters, at least most of the tests. I haven't tought much about conditions, but you are the first contributor, we can specify new confitions for other contributors.

**Comment by MiguhRuiz** [comment]
Should I have to use the same test tools that you use? I usually use ava which is a new test runner. What about publication on NPM? I have seen that you've send the module into it but how can I send updates of it?

**Comment by Javascipt** [comment]
It's ok if you would like to use ava. What is your npm username ?

**Comment by MiguhRuiz** [comment]
Great, thanks! 😄 

> [Link to my NPM profile](https://www.npmjs.com/~miguhruiz)

**Comment by Javascipt** [comment]
You are now co-owner of the package at npmjs : 

```
$ npm owner ls fruit-rethinkdb
javascript <Array.prototype@gmail.com>
miguhruiz <miguhruiz@gmail.com>
```

Enjoy :)
